name: ncov-docs
channels:
  - defaults
dependencies:
  - make
  - pip
  - pip:
    - nextstrain-sphinx-theme>=2022.5
    - recommonmark
    - requests
    - sphinx
    - docutils<0.18
    - sphinx-argparse
    - sphinx-copybutton
    - sphinx-markdown-tables
    - sphinx-tabs
